---
#Master playbook
- hosts: zookeeper
  tags: zookeeper, airavata
  roles:
    - env_setup
    - java
    - zookeeper

- hosts: rabbitmq
  tags: rabbitmq, airavata
  roles:
    - env_setup
    - rabbitmq

- hosts: database
  tags: mysql
  roles:
    - env_setup
    - database

- hosts: wso2is
  tags: wso2is
  roles:
    - env_setup
    - java
    - wso2_is

- hosts: gfac
  tags: gfac, airavata
  roles:
    - env_setup
    - java
    - common
    - gfac

- hosts: api-orch
  tags: api-orch, airavata
  roles:
    - env_setup
    - java
    - common
    - api-orch

- hosts: pga
  tags: pga
  roles:
    - env_setup
    - pga

...
