#
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

---
vhost_servername: "testing.smaltr.scigap.org"
vhost_ssl: True
ssl_certificate_file: "/etc/letsencrypt/live/testing.smaltr.scigap.org/cert.pem"
ssl_certificate_chain_file: "/etc/letsencrypt/live/testing.smaltr.scigap.org/fullchain.pem"
ssl_certificate_key_file: "/etc/letsencrypt/live/testing.smaltr.scigap.org/privkey.pem"

## Keycloak related variables
tenant_domain: "smaltr"
oauth_client_key: "{{ vault_oauth_client_key }}"
oauth_client_secret: "{{ vault_oauth_client_secret }}"

auth_options:
  password:
    name: "smaltr"
  external:
    - name: "CILogon"
      idp_alias: "oidc"

gateway_id: "smaltr"
experiment_data_dir: "{{ user_data_dir }}/django-smaltr"
gateway_data_store_ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyZNwlsy21FKRBVmB8hiO2dunBiVykmLX9OtAURISwRi/ZzCKHBiX10InWO3o1IEjF/VSfZX+LY0FIaDQRsgOwquYNjiQt5kwB3TiGWIG4J2zQxWj6IqDMmaiMvX6SdJcxB7f5/VSDl/FpVc3Hfo7ExG9GRB43fYyXFdBY5ExLgCH1TfMShUDSW1fi1P5BxuE6BJt+faJvZ1bIiuSIgPK+5gsz7eFIfBO29Gkbm2ho0j6MfAN8Il6bnxM1pFhUA1KKMLuiZISC96mnOjHrACwRruJf2pJxTWdiDGQTU9MhYr8TaXzz35hOdFQIVdnkII7cfUOqm7LwaO95MAjbsU9F"

portal_email_host: "smtp.gmail.com"
portal_email_port: 587
portal_email_tls: true
portal_email_username: "pga.airavata@gmail.com"
portal_email_password: "{{ vault_portal_email_password }}"
admin_emails: "[('SGRC', 'sgg@iu.edu'), ('Dimuthu Wannipurage', 'dwannipu@iu.edu'), ('Eroma Abeysinghe', 'eroma.abeysinghe@gmail.com')]"
portal_server_email: "{{ portal_email_username }}"
portal_title: "SMALTR Portal"

...
