---
- name: create group
  group: name="{{group}}"
  become: yes

- name: create user
  user: name="{{user}}"
  become: yes

- name: install required packages
  yum: name="{{item}}" state=latest
  with_item:
    - wget
    - tar
    - git
    - epel-release
    - subversion
    - firewalld
