---
- name: start zookeeper
  service: name=zookeeper state=started
  become: yes

- name: stop zookeeper
  service: name=zookeeper state=stopped
  become: yes

- name: restart zookeeper
  service: name=zookeeper state=restarted
  become: yes
