---
- name: Install Airavata pre-requireties
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - git
    - maven
  become: yes

# Setup airavata source
- name: Create deployment directory {{ deployment_dir }}
  file: path={{ deployment_dir }} state=directory mode=0755

- name: Create source directory
  file: path={{airavata_source_dir}}
        state=directory
        mode=0755
        owner={{ user }}
        group={{ group }}

- name: git checkout from airavata github
  git: repo=https://git-wip-us.apache.org/repos/asf/airavata.git
       dest="{{ airavata_source_dir }}"
       version="{{ git_branch }}"
  register: checkout
  tags: update

- name: Run maven build
  command: mvn clean install -Dmaven.test.skip=true chdir="{{ airavata_source_dir }}/"
  when: (checkout|success) or (checkout|skipped)
  register: build
  tags: update

################################################################################
# copy key store and trust store files
- name: Create KeyStores directory
  file: path="{{ key_stores_location }}"
        state=directory
        owner="{{ user }}" group="{{ group }}"

- name: Transfer airavata.jks KeyStore file
  copy: src="{{ key_store }}"
        dest="{{ key_stores_location }}/{{ key_store }}"
        owner="{{ user }}" group="{{ group }}"

- name: Transfer client trust store KeyStore file
  copy: src="{{ cred_key_store }}"
        dest="{{ key_stores_location }}/{{ cred_key_store }}"
        owner="{{ user }}" group="{{ group }}"
